### ISSUE TITLE
Publish the code in ES5 to npm

### ISSUE THREAD

**Issue by utsavnarayan** [sindresorhus/camelcase#30] opened 2017-10-28 22:48 UTC
'npm run build' fails to minify because index.js is using 'let' and arrow functions.

Refer:
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

I can create a pull-request if you would like to downgrade to ES5.

**Comment by sindresorhus** [comment] 2017-10-29 06:46
Duplicate of #23

**Closed by sindresorhus** 2017-10-29 06:46 UTC
