### ISSUE TITLE
Breaking with IE11

### ISSUE THREAD

**Issue by timbergus** [sindresorhus/camelcase#44] opened 2018-12-11 16:05 UTC
I'm really sorry to say this, but the library is not working with IE11 because of __index.js__ has ECMAScript format, and a fat arrow is breaking our build. We need to develop for IE11 because is a client requirement, so, how can we solve this problem? Could you please upload the library transpiled?

Thanks in advanced.

**Comment by sindresorhus** [comment] 2018-12-11 23:31
Duplicate of #29

**Closed by sindresorhus** 2018-12-11 23:31 UTC
