### ISSUE TITLE
SyntaxError: Invalid regular expression: /[\p{Lu}]/: Invalid escape

### ISSUE THREAD

**Issue by ityancs** [sindresorhus/camelcase#90] opened 2021-11-16 07:45 UTC
const UPPERCASE = /[\p{Lu}]/u;

will throw the exception when deploy。

**Comment by sindresorhus** [comment] 2021-11-16 07:49
Duplicate of #88

**Closed by sindresorhus** 2021-11-16 07:49 UTC

**Comment by ityancs** [comment] 2021-11-16 07:52
@sindresorhus Thank you for your reply. How to add a parser to solve this problem in detail? I think many beginners will still be confused.

**Comment by ityancs** [comment] 2021-11-16 07:54
I actually saw this and that question before, I think you explained it very clearly, but it is still very confusing for beginners. Can you give some examples?

**Comment by sindresorhus** [comment] 2021-11-16 08:06
This is a problem with your build tool, not this package. You should open an issue there instead.
