### ISSUE TITLE
Add notification for "node.js only" support

### ISSUE THREAD

**Issue by valentinpalkovic** [sindresorhus/camelcase#33] opened 2017-12-08 08:00 UTC
I had the very similar issue like some guys before, that i assumed this package is valid also for frontend scripts. After figuring out, why the code is not running on ie11, i found out, that your package is not transpiled. That's totally fine. But please add an appropriate info text within the description, that this package is written mainly for node.js. You can't demand the reading of the source code from every user. This "bug/unexpected behavior" was really not obvious. So please add the note for future usage. :)

**Comment by sindresorhus** [comment] 2017-12-17 00:45
Duplicate of #23.

**Comment by sindresorhus** [comment] 2017-12-17 00:45
It works fine in modern browsers. I can't possibly know what browsers my users want to target. It's up to users to transpile if they need to support older browsers.

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

More info: https://github.com/sindresorhus/ama/issues/446

**Closed by sindresorhus** 2017-12-17 00:45 UTC
